version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3366:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - mysql_server01_data:/var/lib/psql

volumes:
  mysql_server01_data:
